package wxwork

import (
	"errors"
	"net/url"
	"os"
	"time"

	"github.com/spf13/viper"
	"pkg.blksails.net/kf/utils"
)

var DefaultHost = "https://qyapi.weixin.qq.com"

type Client interface {
	ChatdataSetPublicKey(req *ChatdataSetPublicKeyRequest) (*ChatdataSetPublicKeyResponse, error)
	ChatdataGetAuthUserList(req *ChatdataGetAuthUserListRequest) (*ChatdataGetAuthUserListResponse, error)
	ChatdataSetReceiveCallback(req *ChatdataSetReceiveCallbackRequest) (*ChatdataSetReceiveCallbackResponse, error)
	ChatdataSyncCallProgram(req *ChatdataSyncCallProgramRequest) (*ChatdataSyncCallProgramResponse, error)
	ChatdataAsyncProgramResult(req *ChatdataAsyncProgramResultRequest) (*ChatdataAsyncProgramResultResponse, error)
	ChatdataGetHideSensitiveinfoConfig(req *ChatdataGetHideSensitiveinfoConfigRequest) (*ChatdataGetHideSensitiveinfoConfigResponse, error)
	AgentGetAdminList(req *AgentGetAdminListRequest) (*AgentGetAdminListResponse, error)
	SecurityGetServerDomainIp(req *SecurityGetServerDomainIpRequest) (*SecurityGetServerDomainIpResponse, error)
	ChatdataOpenDebugMode(req *ChatdataOpenDebugModeRequest) (*ChatdataOpenDebugModeResponse, error)
	ChatdataCloseDebugMode(req *ChatdataCloseDebugModeRequest) (*ChatdataCloseDebugModeResponse, error)
	ChatdataGetLogLevel(req *ChatdataGetLogLevelRequest) (*ChatdataGetLogLevelResponse, error)
	ChatdataCheckDebugMode(req *ChatdataCheckDebugModeRequest) (*ChatdataCheckDebugModeResponse, error)
	SecurityGetScreenOperRecord(req *SecurityGetScreenOperRecordRequest) (*SecurityGetScreenOperRecordResponse, error)
	ExternalcontactCustomerAcquisitionGetChatInfo(req *ExternalcontactCustomerAcquisitionGetChatInfoRequest) (*ExternalcontactCustomerAcquisitionGetChatInfoResponse, error)
	ServiceGetAccountBalance(req *ServiceGetAccountBalanceRequest) (*ServiceGetAccountBalanceResponse, error)
	ChatdataUploadMedia(req *ChatdataUploadMediaRequest) (*ChatdataUploadMediaResponse, error)
	SchoolUserCreateStudent(req *SchoolUserCreateStudentRequest) (*SchoolUserCreateStudentResponse, error)
	SchoolUserDeleteStudent(req *SchoolUserDeleteStudentRequest) (*SchoolUserDeleteStudentResponse, error)
	SchoolUserUpdateStudent(req *SchoolUserUpdateStudentRequest) (*SchoolUserUpdateStudentResponse, error)
	SchoolUserBatchCreateStudent(req *SchoolUserBatchCreateStudentRequest) (*SchoolUserBatchCreateStudentResponse, error)
	SchoolUserBatchDeleteStudent(req *SchoolUserBatchDeleteStudentRequest) (*SchoolUserBatchDeleteStudentResponse, error)
	SchoolUserBatchUpdateStudent(req *SchoolUserBatchUpdateStudentRequest) (*SchoolUserBatchUpdateStudentResponse, error)
	SchoolUserCreateParent(req *SchoolUserCreateParentRequest) (*SchoolUserCreateParentResponse, error)
	SchoolUserDeleteParent(req *SchoolUserDeleteParentRequest) (*SchoolUserDeleteParentResponse, error)
	SchoolUserUpdateParent(req *SchoolUserUpdateParentRequest) (*SchoolUserUpdateParentResponse, error)
	SchoolUserBatchCreateParent(req *SchoolUserBatchCreateParentRequest) (*SchoolUserBatchCreateParentResponse, error)
	SchoolUserBatchDeleteParent(req *SchoolUserBatchDeleteParentRequest) (*SchoolUserBatchDeleteParentResponse, error)
	SchoolUserBatchUpdateParent(req *SchoolUserBatchUpdateParentRequest) (*SchoolUserBatchUpdateParentResponse, error)
	SchoolSetArchSyncMode(req *SchoolSetArchSyncModeRequest) (*SchoolSetArchSyncModeResponse, error)
	SchoolDepartmentCreate(req *SchoolDepartmentCreateRequest) (*SchoolDepartmentCreateResponse, error)
	SchoolDepartmentUpdate(req *SchoolDepartmentUpdateRequest) (*SchoolDepartmentUpdateResponse, error)
	SchoolDepartmentDelete(req *SchoolDepartmentDeleteRequest) (*SchoolDepartmentDeleteResponse, error)
	SchoolSetUpgradeInfo(req *SchoolSetUpgradeInfoRequest) (*SchoolSetUpgradeInfoResponse, error)
	SecurityMemberOperLogList(req *SecurityMemberOperLogListRequest) (*SecurityMemberOperLogListResponse, error)
	SecurityAdminOperLogList(req *SecurityAdminOperLogListRequest) (*SecurityAdminOperLogListResponse, error)
	ExmailPublicmailGetAuthCodeList(req *ExmailPublicmailGetAuthCodeListRequest) (*ExmailPublicmailGetAuthCodeListResponse, error)
	ExmailPublicmailDeleteAuthCode(req *ExmailPublicmailDeleteAuthCodeRequest) (*ExmailPublicmailDeleteAuthCodeResponse, error)
	WedocSmartsheetContentPrivDeleteRule(req *WedocSmartsheetContentPrivDeleteRuleRequest) (*WedocSmartsheetContentPrivDeleteRuleResponse, error)
	WedocSmartsheetAddSheet(req *WedocSmartsheetAddSheetRequest) (*WedocSmartsheetAddSheetResponse, error)
	WedocSmartsheetDeleteSheet(req *WedocSmartsheetDeleteSheetRequest) (*WedocSmartsheetDeleteSheetResponse, error)
	WedocSmartsheetUpdateSheet(req *WedocSmartsheetUpdateSheetRequest) (*WedocSmartsheetUpdateSheetResponse, error)
	WedocSmartsheetAddView(req *WedocSmartsheetAddViewRequest) (*WedocSmartsheetAddViewResponse, error)
	WedocSmartsheetDeleteViews(req *WedocSmartsheetDeleteViewsRequest) (*WedocSmartsheetDeleteViewsResponse, error)
	WedocSmartsheetUpdateView(req *WedocSmartsheetUpdateViewRequest) (*WedocSmartsheetUpdateViewResponse, error)
	WedocSmartsheetAddFields(req *WedocSmartsheetAddFieldsRequest) (*WedocSmartsheetAddFieldsResponse, error)
	WedocSmartsheetDeleteFields(req *WedocSmartsheetDeleteFieldsRequest) (*WedocSmartsheetDeleteFieldsResponse, error)
	WedocSmartsheetUpdateFields(req *WedocSmartsheetUpdateFieldsRequest) (*WedocSmartsheetUpdateFieldsResponse, error)
	WedocSmartsheetDeleteRecords(req *WedocSmartsheetDeleteRecordsRequest) (*WedocSmartsheetDeleteRecordsResponse, error)
	WedocSmartsheetUpdateRecords(req *WedocSmartsheetUpdateRecordsRequest) (*WedocSmartsheetUpdateRecordsResponse, error)
	WedocSmartsheetAddRecords(req *WedocSmartsheetAddRecordsRequest) (*WedocSmartsheetAddRecordsResponse, error)
	ChatdataGetCorpAuthInfo(req *ChatdataGetCorpAuthInfoRequest) (*ChatdataGetCorpAuthInfoResponse, error)
	AdvancedAPICreateOrder(req *AdvancedAPICreateOrderRequest) (*AdvancedAPICreateOrderResponse, error)
	AdvancedAPICancelOrder(req *AdvancedAPICancelOrderRequest) (*AdvancedAPICancelOrderResponse, error)
	AdvancedAPISubmitPay(req *AdvancedAPISubmitPayRequest) (*AdvancedAPISubmitPayResponse, error)
	AdvancedAPIListOrder(req *AdvancedAPIListOrderRequest) (*AdvancedAPIListOrderResponse, error)
	AdvancedAPIGetOrder(req *AdvancedAPIGetOrderRequest) (*AdvancedAPIGetOrderResponse, error)
	AdvancedAPIGetCorpBuyInfo(req *AdvancedAPIGetCorpBuyInfoRequest) (*AdvancedAPIGetCorpBuyInfoResponse, error)
	ServiceV2GetPermanentCode(req *ServiceV2GetPermanentCodeRequest) (*ServiceV2GetPermanentCodeResponse, error)
	ServiceV2GetAuthInfo(req *ServiceV2GetAuthInfoRequest) (*ServiceV2GetAuthInfoResponse, error)
	WedocSmartsheetGroupchatList(req *WedocSmartsheetGroupchatListRequest) (*WedocSmartsheetGroupchatListResponse, error)
	UserGetuserinfo(req *UserGetuserinfoRequest) (*UserGetuserinfoResponse, error)
	WedocSmartsheetGroupchatGet(req *WedocSmartsheetGroupchatGetRequest) (*WedocSmartsheetGroupchatGetResponse, error)
	WedocSmartsheetGroupchatUpdate(req *WedocSmartsheetGroupchatUpdateRequest) (*WedocSmartsheetGroupchatUpdateResponse, error)
	WedocSmartsheetAddFieldGroup(req *WedocSmartsheetAddFieldGroupRequest) (*WedocSmartsheetAddFieldGroupResponse, error)
	WedocSmartsheetUpdateFieldGroup(req *WedocSmartsheetUpdateFieldGroupRequest) (*WedocSmartsheetUpdateFieldGroupResponse, error)
	WedocSmartsheetDeleteFieldGroups(req *WedocSmartsheetDeleteFieldGroupsRequest) (*WedocSmartsheetDeleteFieldGroupsResponse, error)
	WedocSmartsheetGetFieldGroups(req *WedocSmartsheetGetFieldGroupsRequest) (*WedocSmartsheetGetFieldGroupsResponse, error)
	IDconvertBatchExternalUseridToPendingID(req *IDconvertBatchExternalUseridToPendingIDRequest) (*IDconvertBatchExternalUseridToPendingIDResponse, error)
	WedocSmartsheetGetSheet(req *WedocSmartsheetGetSheetRequest) (*WedocSmartsheetGetSheetResponse, error)
	WedocSmartsheetGetViews(req *WedocSmartsheetGetViewsRequest) (*WedocSmartsheetGetViewsResponse, error)
	WedocSmartsheetGetFields(req *WedocSmartsheetGetFieldsRequest) (*WedocSmartsheetGetFieldsResponse, error)
	WedocSmartsheetGetRecords(req *WedocSmartsheetGetRecordsRequest) (*WedocSmartsheetGetRecordsResponse, error)
	WedocDocumentGet(req *WedocDocumentGetRequest) (*WedocDocumentGetResponse, error)
	WedocSpreadsheetBatchUpdate(req *WedocSpreadsheetBatchUpdateRequest) (*WedocSpreadsheetBatchUpdateResponse, error)
	UserCreate(req *UserCreateRequest) (*UserCreateResponse, error)
	UserGet(req *UserGetRequest) (*UserGetResponse, error)
	UserUpdate(req *UserUpdateRequest) (*UserUpdateResponse, error)
	UserDelete(req *UserDeleteRequest) (*UserDeleteResponse, error)
	UserBatchdelete(req *UserBatchdeleteRequest) (*UserBatchdeleteResponse, error)
	UserSimplelist(req *UserSimplelistRequest) (*UserSimplelistResponse, error)
	UserList(req *UserListRequest) (*UserListResponse, error)
	UserConvertToUserid(req *UserConvertToUseridRequest) (*UserConvertToUseridResponse, error)
	UserAuthsucc(req *UserAuthsuccRequest) (*UserAuthsuccResponse, error)
	DepartmentCreate(req *DepartmentCreateRequest) (*DepartmentCreateResponse, error)
	DepartmentUpdate(req *DepartmentUpdateRequest) (*DepartmentUpdateResponse, error)
	DepartmentDelete(req *DepartmentDeleteRequest) (*DepartmentDeleteResponse, error)
	TagCreate(req *TagCreateRequest) (*TagCreateResponse, error)
	TagUpdate(req *TagUpdateRequest) (*TagUpdateResponse, error)
	TagDelete(req *TagDeleteRequest) (*TagDeleteResponse, error)
	TagGet(req *TagGetRequest) (*TagGetResponse, error)
	TagAddtagusers(req *TagAddtagusersRequest) (*TagAddtagusersResponse, error)
	TagDeltagusers(req *TagDeltagusersRequest) (*TagDeltagusersResponse, error)
	TagList(req *TagListRequest) (*TagListResponse, error)
	AgentList(req *AgentListRequest) (*AgentListResponse, error)
	AgentSet(req *AgentSetRequest) (*AgentSetResponse, error)
	MenuCreate(req *MenuCreateRequest) (*MenuCreateResponse, error)
	MenuGet(req *MenuGetRequest) (*MenuGetResponse, error)
	MenuDelete(req *MenuDeleteRequest) (*MenuDeleteResponse, error)
	MessageSend(req *MessageSendRequest) (*MessageSendResponse, error)
	Getcallbackip(req *GetcallbackipRequest) (*GetcallbackipResponse, error)
	AppchatCreate(req *AppchatCreateRequest) (*AppchatCreateResponse, error)
	AppchatSend(req *AppchatSendRequest) (*AppchatSendResponse, error)
	MediaUpload(req *MediaUploadRequest) (*MediaUploadResponse, error)
	MediaGet(req *MediaGetRequest) (*MediaGetResponse, error)
	MediaGetJssdk(req *MediaGetJssdkRequest) (*MediaGetJssdkResponse, error)
	MediaUploadimg(req *MediaUploadimgRequest) (*MediaUploadimgResponse, error)
	CheckinGetcheckindata(req *CheckinGetcheckindataRequest) (*CheckinGetcheckindataResponse, error)
	CheckinGetcheckinoption(req *CheckinGetcheckinoptionRequest) (*CheckinGetcheckinoptionResponse, error)
	CorpGetopenapprovaldata(req *CorpGetopenapprovaldataRequest) (*CorpGetopenapprovaldataResponse, error)
	CardInvoiceReimburseGetinvoiceinfo(req *CardInvoiceReimburseGetinvoiceinfoRequest) (*CardInvoiceReimburseGetinvoiceinfoResponse, error)
	CardInvoiceReimburseUpdateinvoicestatus(req *CardInvoiceReimburseUpdateinvoicestatusRequest) (*CardInvoiceReimburseUpdateinvoicestatusResponse, error)
	CardInvoiceReimburseUpdatestatusbatch(req *CardInvoiceReimburseUpdatestatusbatchRequest) (*CardInvoiceReimburseUpdatestatusbatchResponse, error)
	CardInvoiceReimburseGetinvoiceinfobatch(req *CardInvoiceReimburseGetinvoiceinfobatchRequest) (*CardInvoiceReimburseGetinvoiceinfobatchResponse, error)
	Gettoken(req *GettokenRequest) (*GettokenResponse, error)
	TicketGet(req *TicketGetRequest) (*TicketGetResponse, error)
	ServiceGetRegisterCode(req *ServiceGetRegisterCodeRequest) (*ServiceGetRegisterCodeResponse, error)
	ServiceGetRegisterInfo(req *ServiceGetRegisterInfoRequest) (*ServiceGetRegisterInfoResponse, error)
	AgentSetScope(req *AgentSetScopeRequest) (*AgentSetScopeResponse, error)
	SyncContactSyncSuccess(req *SyncContactSyncSuccessRequest) (*SyncContactSyncSuccessResponse, error)
	ServiceGetProviderToken(req *ServiceGetProviderTokenRequest) (*ServiceGetProviderTokenResponse, error)
	ServiceGetSuiteToken(req *ServiceGetSuiteTokenRequest) (*ServiceGetSuiteTokenResponse, error)
	ServiceGetPreAuthCode(req *ServiceGetPreAuthCodeRequest) (*ServiceGetPreAuthCodeResponse, error)
	ServiceSetSessionInfo(req *ServiceSetSessionInfoRequest) (*ServiceSetSessionInfoResponse, error)
	ServiceGetCorpToken(req *ServiceGetCorpTokenRequest) (*ServiceGetCorpTokenResponse, error)
	BatchInvite(req *BatchInviteRequest) (*BatchInviteResponse, error)
	BatchSyncuser(req *BatchSyncuserRequest) (*BatchSyncuserResponse, error)
	BatchReplaceuser(req *BatchReplaceuserRequest) (*BatchReplaceuserResponse, error)
	BatchReplaceparty(req *BatchReplacepartyRequest) (*BatchReplacepartyResponse, error)
	BatchGetresult(req *BatchGetresultRequest) (*BatchGetresultResponse, error)
	AuthGetuserinfo(req *AuthGetuserinfoRequest) (*AuthGetuserinfoResponse, error)
	ServiceAuthGetuserinfo3rd(req *ServiceAuthGetuserinfo3rdRequest) (*ServiceAuthGetuserinfo3rdResponse, error)
	ServiceAuthGetuserdetail3rd(req *ServiceAuthGetuserdetail3rdRequest) (*ServiceAuthGetuserdetail3rdResponse, error)
	MiniprogramJscode2session(req *MiniprogramJscode2sessionRequest) (*MiniprogramJscode2sessionResponse, error)
	CorpGetapprovaldata(req *CorpGetapprovaldataRequest) (*CorpGetapprovaldataResponse, error)
	ExternalcontactMessageSend(req *ExternalcontactMessageSendRequest) (*ExternalcontactMessageSendResponse, error)
	MsgauditGetPermitUserList(req *MsgauditGetPermitUserListRequest) (*MsgauditGetPermitUserListResponse, error)
	PstnccCall(req *PstnccCallRequest) (*PstnccCallResponse, error)
	PstnccGetstates(req *PstnccGetstatesRequest) (*PstnccGetstatesResponse, error)
	ExternalcontactGet(req *ExternalcontactGetRequest) (*ExternalcontactGetResponse, error)
	UserGetuserid(req *UserGetuseridRequest) (*UserGetuseridResponse, error)
	ServiceGetuserinfo3rd(req *ServiceGetuserinfo3rdRequest) (*ServiceGetuserinfo3rdResponse, error)
	CorpGetJoinQrcode(req *CorpGetJoinQrcodeRequest) (*CorpGetJoinQrcodeResponse, error)
	WebhookUploadMedia(req *WebhookUploadMediaRequest) (*WebhookUploadMediaResponse, error)
	MsgauditGetRobotInfo(req *MsgauditGetRobotInfoRequest) (*MsgauditGetRobotInfoResponse, error)
	MsgauditCheckRoomAgree(req *MsgauditCheckRoomAgreeRequest) (*MsgauditCheckRoomAgreeResponse, error)
	OaGetapprovalinfo(req *OaGetapprovalinfoRequest) (*OaGetapprovalinfoResponse, error)
	ServiceContactBatchsearch(req *ServiceContactBatchsearchRequest) (*ServiceContactBatchsearchResponse, error)
	ServiceContactIDTranslate(req *ServiceContactIDTranslateRequest) (*ServiceContactIDTranslateResponse, error)
	OaApplyevent(req *OaApplyeventRequest) (*OaApplyeventResponse, error)
	ServiceBatchGetresult(req *ServiceBatchGetresultRequest) (*ServiceBatchGetresultResponse, error)
	ServiceGetOrder(req *ServiceGetOrderRequest) (*ServiceGetOrderResponse, error)
	ServiceGetOrderList(req *ServiceGetOrderListRequest) (*ServiceGetOrderListResponse, error)
	ServiceGetPermanentCode(req *ServiceGetPermanentCodeRequest) (*ServiceGetPermanentCodeResponse, error)
	ServiceGetAuthInfo(req *ServiceGetAuthInfoRequest) (*ServiceGetAuthInfoResponse, error)
	ServiceProlongTry(req *ServiceProlongTryRequest) (*ServiceProlongTryResponse, error)
	OaGettemplatedetail(req *OaGettemplatedetailRequest) (*OaGettemplatedetailResponse, error)
	OaGetapprovaldetail(req *OaGetapprovaldetailRequest) (*OaGetapprovaldetailResponse, error)
	SchoolUserGet(req *SchoolUserGetRequest) (*SchoolUserGetResponse, error)
	SchoolUserList(req *SchoolUserListRequest) (*SchoolUserListResponse, error)
	ServiceContactSort(req *ServiceContactSortRequest) (*ServiceContactSortResponse, error)
	ExternalcontactList(req *ExternalcontactListRequest) (*ExternalcontactListResponse, error)
	ExternalcontactRemark(req *ExternalcontactRemarkRequest) (*ExternalcontactRemarkResponse, error)
	ExternalcontactDelCorpTag(req *ExternalcontactDelCorpTagRequest) (*ExternalcontactDelCorpTagResponse, error)
	ExternalcontactMarkTag(req *ExternalcontactMarkTagRequest) (*ExternalcontactMarkTagResponse, error)
	ExternalcontactGroupchatList(req *ExternalcontactGroupchatListRequest) (*ExternalcontactGroupchatListResponse, error)
	ExternalcontactGroupchatGet(req *ExternalcontactGroupchatGetRequest) (*ExternalcontactGroupchatGetResponse, error)
	ExternalcontactGetUnassignedList(req *ExternalcontactGetUnassignedListRequest) (*ExternalcontactGetUnassignedListResponse, error)
	ExternalcontactTransferCustomer(req *ExternalcontactTransferCustomerRequest) (*ExternalcontactTransferCustomerResponse, error)
	ExternalcontactGroupchatTransfer(req *ExternalcontactGroupchatTransferRequest) (*ExternalcontactGroupchatTransferResponse, error)
	ExternalcontactGetUserBehaviorData(req *ExternalcontactGetUserBehaviorDataRequest) (*ExternalcontactGetUserBehaviorDataResponse, error)
	ExternalcontactGroupchatStatisticGroupByDay(req *ExternalcontactGroupchatStatisticGroupByDayRequest) (*ExternalcontactGroupchatStatisticGroupByDayResponse, error)
	ExternalcontactAddMsgTemplate(req *ExternalcontactAddMsgTemplateRequest) (*ExternalcontactAddMsgTemplateResponse, error)
	ExternalcontactSendWelcomeMsg(req *ExternalcontactSendWelcomeMsgRequest) (*ExternalcontactSendWelcomeMsgResponse, error)
	ExternalcontactGetSubscribeQrCode(req *ExternalcontactGetSubscribeQrCodeRequest) (*ExternalcontactGetSubscribeQrCodeResponse, error)
	ExternalcontactCloseTempChat(req *ExternalcontactCloseTempChatRequest) (*ExternalcontactCloseTempChatResponse, error)
	ExternalcontactGroupchatDelJoinWay(req *ExternalcontactGroupchatDelJoinWayRequest) (*ExternalcontactGroupchatDelJoinWayResponse, error)
	ExternalcontactGetSubscribeMode(req *ExternalcontactGetSubscribeModeRequest) (*ExternalcontactGetSubscribeModeResponse, error)
	ExternalcontactConvertToOpenid(req *ExternalcontactConvertToOpenidRequest) (*ExternalcontactConvertToOpenidResponse, error)
	SchoolDepartmentList(req *SchoolDepartmentListRequest) (*SchoolDepartmentListResponse, error)
	ExternalcontactGroupWelcomeTemplateDel(req *ExternalcontactGroupWelcomeTemplateDelRequest) (*ExternalcontactGroupWelcomeTemplateDelResponse, error)
	SchoolSetChatCreateMode(req *SchoolSetChatCreateModeRequest) (*SchoolSetChatCreateModeResponse, error)
	SchoolUserListParent(req *SchoolUserListParentRequest) (*SchoolUserListParentResponse, error)
	ExternalcontactBatchToExternalUserid(req *ExternalcontactBatchToExternalUseridRequest) (*ExternalcontactBatchToExternalUseridResponse, error)
	GetAPIDomainIp(req *GetAPIDomainIpRequest) (*GetAPIDomainIpResponse, error)
	AgentGetWorkbenchData(req *AgentGetWorkbenchDataRequest) (*AgentGetWorkbenchDataResponse, error)
	ExternalcontactGetFollowUserList(req *ExternalcontactGetFollowUserListRequest) (*ExternalcontactGetFollowUserListResponse, error)
	OaApprovalCopytemplate(req *OaApprovalCopytemplateRequest) (*OaApprovalCopytemplateResponse, error)
	SchoolGetTeacherViewMode(req *SchoolGetTeacherViewModeRequest) (*SchoolGetTeacherViewModeResponse, error)
	MsgauditGroupchatGet(req *MsgauditGroupchatGetRequest) (*MsgauditGroupchatGetResponse, error)
	ExternalcontactBatchGetByUser(req *ExternalcontactBatchGetByUserRequest) (*ExternalcontactBatchGetByUserResponse, error)
	ExternalcontactGetMomentComments(req *ExternalcontactGetMomentCommentsRequest) (*ExternalcontactGetMomentCommentsResponse, error)
	ExternalcontactGetGroupmsgSendResult(req *ExternalcontactGetGroupmsgSendResultRequest) (*ExternalcontactGetGroupmsgSendResultResponse, error)
	MiniprogramTransferSession(req *MiniprogramTransferSessionRequest) (*MiniprogramTransferSessionResponse, error)
	CorpgroupCorpGettoken(req *CorpgroupCorpGettokenRequest) (*CorpgroupCorpGettokenResponse, error)
	CheckinGetcheckinDaydata(req *CheckinGetcheckinDaydataRequest) (*CheckinGetcheckinDaydataResponse, error)
	OaVacationGetcorpconf(req *OaVacationGetcorpconfRequest) (*OaVacationGetcorpconfResponse, error)
	OaVacationGetuservacationquota(req *OaVacationGetuservacationquotaRequest) (*OaVacationGetuservacationquotaResponse, error)
	OaVacationSetoneuserquota(req *OaVacationSetoneuserquotaRequest) (*OaVacationSetoneuserquotaResponse, error)
	CheckinAddcheckinuserface(req *CheckinAddcheckinuserfaceRequest) (*CheckinAddcheckinuserfaceResponse, error)
	CheckinGetcheckinschedulist(req *CheckinGetcheckinschedulistRequest) (*CheckinGetcheckinschedulistResponse, error)
	CheckinGetcorpcheckinoption(req *CheckinGetcorpcheckinoptionRequest) (*CheckinGetcorpcheckinoptionResponse, error)
	CheckinSetcheckinschedulist(req *CheckinSetcheckinschedulistRequest) (*CheckinSetcheckinschedulistResponse, error)
	CheckinGetcheckinMonthdata(req *CheckinGetcheckinMonthdataRequest) (*CheckinGetcheckinMonthdataResponse, error)
	OaJournalGetRecordList(req *OaJournalGetRecordListRequest) (*OaJournalGetRecordListResponse, error)
	OaJournalGetRecordDetail(req *OaJournalGetRecordDetailRequest) (*OaJournalGetRecordDetailResponse, error)
	OaJournalGetStatList(req *OaJournalGetStatListRequest) (*OaJournalGetStatListResponse, error)
	CorpgroupCorpListAppShareInfo(req *CorpgroupCorpListAppShareInfoRequest) (*CorpgroupCorpListAppShareInfoResponse, error)
	ReportResidentGetGridInfo(req *ReportResidentGetGridInfoRequest) (*ReportResidentGetGridInfoResponse, error)
	ReportResidentGetCorpStatus(req *ReportResidentGetCorpStatusRequest) (*ReportResidentGetCorpStatusResponse, error)
	ReportResidentGetUserStatus(req *ReportResidentGetUserStatusRequest) (*ReportResidentGetUserStatusResponse, error)
	ReportResidentCategoryStatistic(req *ReportResidentCategoryStatisticRequest) (*ReportResidentCategoryStatisticResponse, error)
	ReportResidentGetOrderList(req *ReportResidentGetOrderListRequest) (*ReportResidentGetOrderListResponse, error)
	ReportResidentGetOrderInfo(req *ReportResidentGetOrderInfoRequest) (*ReportResidentGetOrderInfoResponse, error)
	ReportPatrolGetGridInfo(req *ReportPatrolGetGridInfoRequest) (*ReportPatrolGetGridInfoResponse, error)
	ReportPatrolGetCorpStatus(req *ReportPatrolGetCorpStatusRequest) (*ReportPatrolGetCorpStatusResponse, error)
	ReportPatrolGetUserStatus(req *ReportPatrolGetUserStatusRequest) (*ReportPatrolGetUserStatusResponse, error)
	ReportPatrolCategoryStatistic(req *ReportPatrolCategoryStatisticRequest) (*ReportPatrolCategoryStatisticResponse, error)
	ReportPatrolGetOrderInfo(req *ReportPatrolGetOrderInfoRequest) (*ReportPatrolGetOrderInfoResponse, error)
	ReportPatrolGetOrderList(req *ReportPatrolGetOrderListRequest) (*ReportPatrolGetOrderListResponse, error)
	OaMeetingroomDel(req *OaMeetingroomDelRequest) (*OaMeetingroomDelResponse, error)
	OaMeetingroomBookinfoGet(req *OaMeetingroomBookinfoGetRequest) (*OaMeetingroomBookinfoGetResponse, error)
	LivingGetUserAllLivingid(req *LivingGetUserAllLivingidRequest) (*LivingGetUserAllLivingidResponse, error)
	LivingGetLivingInfo(req *LivingGetLivingInfoRequest) (*LivingGetLivingInfoResponse, error)
	LivingGetWatchStat(req *LivingGetWatchStatRequest) (*LivingGetWatchStatResponse, error)
	LivingCreate(req *LivingCreateRequest) (*LivingCreateResponse, error)
	LivingCancel(req *LivingCancelRequest) (*LivingCancelResponse, error)
	LivingModify(req *LivingModifyRequest) (*LivingModifyResponse, error)
	LivingGetLivingCode(req *LivingGetLivingCodeRequest) (*LivingGetLivingCodeResponse, error)
	OaCalendarAdd(req *OaCalendarAddRequest) (*OaCalendarAddResponse, error)
	OaScheduleAdd(req *OaScheduleAddRequest) (*OaScheduleAddResponse, error)
	WedriveSpaceCreate(req *WedriveSpaceCreateRequest) (*WedriveSpaceCreateResponse, error)
	WedriveSpaceAclAdd(req *WedriveSpaceAclAddRequest) (*WedriveSpaceAclAddResponse, error)
	WedriveFileList(req *WedriveFileListRequest) (*WedriveFileListResponse, error)
	WedriveFileAclAdd(req *WedriveFileAclAddRequest) (*WedriveFileAclAddResponse, error)
	DialGetDialRecord(req *DialGetDialRecordRequest) (*DialGetDialRecordResponse, error)
	ExternalpaySetMchUseScope(req *ExternalpaySetMchUseScopeRequest) (*ExternalpaySetMchUseScopeResponse, error)
	ExternalpayGetBillList(req *ExternalpayGetBillListRequest) (*ExternalpayGetBillListResponse, error)
	HealthGetHealthReportStat(req *HealthGetHealthReportStatRequest) (*HealthGetHealthReportStatResponse, error)
	HealthGetReportJobids(req *HealthGetReportJobidsRequest) (*HealthGetReportJobidsResponse, error)
	HealthGetReportJobInfo(req *HealthGetReportJobInfoRequest) (*HealthGetReportJobInfoResponse, error)
	HealthGetReportAnswer(req *HealthGetReportAnswerRequest) (*HealthGetReportAnswerResponse, error)
	MeetingCreate(req *MeetingCreateRequest) (*MeetingCreateResponse, error)
	MeetingGetUserMeetingid(req *MeetingGetUserMeetingidRequest) (*MeetingGetUserMeetingidResponse, error)
	MeetingGetInfo(req *MeetingGetInfoRequest) (*MeetingGetInfoResponse, error)
	MeetingCancel(req *MeetingCancelRequest) (*MeetingCancelResponse, error)
	MeetingUpdate(req *MeetingUpdateRequest) (*MeetingUpdateResponse, error)
	LivingDeleteReplayData(req *LivingDeleteReplayDataRequest) (*LivingDeleteReplayDataResponse, error)
	SchoolLivingGetLivingInfo(req *SchoolLivingGetLivingInfoRequest) (*SchoolLivingGetLivingInfoResponse, error)
	SchoolLivingGetWatchStat(req *SchoolLivingGetWatchStatRequest) (*SchoolLivingGetWatchStatResponse, error)
	SchoolLivingGetUnwatchStat(req *SchoolLivingGetUnwatchStatRequest) (*SchoolLivingGetUnwatchStatResponse, error)
	ExternalcontactResignedTransferCustomer(req *ExternalcontactResignedTransferCustomerRequest) (*ExternalcontactResignedTransferCustomerResponse, error)
	ExternalcontactResignedTransferResult(req *ExternalcontactResignedTransferResultRequest) (*ExternalcontactResignedTransferResultResponse, error)
	ExternalcontactTransferResult(req *ExternalcontactTransferResultRequest) (*ExternalcontactTransferResultResponse, error)
	HardwareGetHardwareCheckinData(req *HardwareGetHardwareCheckinDataRequest) (*HardwareGetHardwareCheckinDataResponse, error)
	GetLaunchCode(req *GetLaunchCodeRequest) (*GetLaunchCodeResponse, error)
	LivingGetLivingShareInfo(req *LivingGetLivingShareInfoRequest) (*LivingGetLivingShareInfoResponse, error)
	SchoolGetPaymentResult(req *SchoolGetPaymentResultRequest) (*SchoolGetPaymentResultResponse, error)
	SchoolGetTrade(req *SchoolGetTradeRequest) (*SchoolGetTradeResponse, error)
	ReportGridAdd(req *ReportGridAddRequest) (*ReportGridAddResponse, error)
	ReportGridUpdate(req *ReportGridUpdateRequest) (*ReportGridUpdateResponse, error)
	ReportGridDelete(req *ReportGridDeleteRequest) (*ReportGridDeleteResponse, error)
	ReportGridList(req *ReportGridListRequest) (*ReportGridListResponse, error)
	ReportGridGetUserGridInfo(req *ReportGridGetUserGridInfoRequest) (*ReportGridGetUserGridInfoResponse, error)
	UserListMemberAuth(req *UserListMemberAuthRequest) (*UserListMemberAuthResponse, error)
	UserCheckMemberAuth(req *UserCheckMemberAuthRequest) (*UserCheckMemberAuthResponse, error)
	ReportGridAddCata(req *ReportGridAddCataRequest) (*ReportGridAddCataResponse, error)
	ReportGridUpdateCata(req *ReportGridUpdateCataRequest) (*ReportGridUpdateCataResponse, error)
	ReportGridDeleteCata(req *ReportGridDeleteCataRequest) (*ReportGridDeleteCataResponse, error)
	ReportGridListCata(req *ReportGridListCataRequest) (*ReportGridListCataResponse, error)
	KFServicerList(req *KFServicerListRequest) (*KFServicerListResponse, error)
	KFServicerAdd(req *KFServicerAddRequest) (*KFServicerAddResponse, error)
	KFServicerDel(req *KFServicerDelRequest) (*KFServicerDelResponse, error)
	KFAccountList(req *KFAccountListRequest) (*KFAccountListResponse, error)
	KFAccountAdd(req *KFAccountAddRequest) (*KFAccountAddResponse, error)
	KFAccountDel(req *KFAccountDelRequest) (*KFAccountDelResponse, error)
	KFAccountUpdate(req *KFAccountUpdateRequest) (*KFAccountUpdateResponse, error)
	KFAddContactWay(req *KFAddContactWayRequest) (*KFAddContactWayResponse, error)
	KFServiceStateTrans(req *KFServiceStateTransRequest) (*KFServiceStateTransResponse, error)
	KFSyncMsg(req *KFSyncMsgRequest) (*KFSyncMsgResponse, error)
	KFCustomerCancelUpgradeService(req *KFCustomerCancelUpgradeServiceRequest) (*KFCustomerCancelUpgradeServiceResponse, error)
	KFSendMsg(req *KFSendMsgRequest) (*KFSendMsgResponse, error)
	ExternalcontactOpengidToChatid(req *ExternalcontactOpengidToChatidRequest) (*ExternalcontactOpengidToChatidResponse, error)
	ExportSimpleUser(req *ExportSimpleUserRequest) (*ExportSimpleUserResponse, error)
	ExportUser(req *ExportUserRequest) (*ExportUserResponse, error)
	ExportDepartment(req *ExportDepartmentRequest) (*ExportDepartmentResponse, error)
	ExportTaguser(req *ExportTaguserRequest) (*ExportTaguserResponse, error)
	ExportGetResult(req *ExportGetResultRequest) (*ExportGetResultResponse, error)
	MessageRecall(req *MessageRecallRequest) (*MessageRecallResponse, error)
	ExternalcontactDelStrategyTag(req *ExternalcontactDelStrategyTagRequest) (*ExternalcontactDelStrategyTagResponse, error)
	ExternalcontactCustomerStrategyDel(req *ExternalcontactCustomerStrategyDelRequest) (*ExternalcontactCustomerStrategyDelResponse, error)
	MessageUpdateTemplateCard(req *MessageUpdateTemplateCardRequest) (*MessageUpdateTemplateCardResponse, error)
	ExternalcontactMomentStrategyDel(req *ExternalcontactMomentStrategyDelRequest) (*ExternalcontactMomentStrategyDelResponse, error)
	UserListSelectedTicketUser(req *UserListSelectedTicketUserRequest) (*UserListSelectedTicketUserResponse, error)
	SchoolAgentGetAllowScope(req *SchoolAgentGetAllowScopeRequest) (*SchoolAgentGetAllowScopeResponse, error)
	KFSendMsgOnEvent(req *KFSendMsgOnEventRequest) (*KFSendMsgOnEventResponse, error)
	ExternalcontactGetMomentTaskResult(req *ExternalcontactGetMomentTaskResultRequest) (*ExternalcontactGetMomentTaskResultResponse, error)
	ExternalcontactDeleteProductAlbum(req *ExternalcontactDeleteProductAlbumRequest) (*ExternalcontactDeleteProductAlbumResponse, error)
	ExternalcontactDelInterceptRule(req *ExternalcontactDelInterceptRuleRequest) (*ExternalcontactDelInterceptRuleResponse, error)
	MediaUploadAttachment(req *MediaUploadAttachmentRequest) (*MediaUploadAttachmentResponse, error)
	KFCustomerBatchget(req *KFCustomerBatchgetRequest) (*KFCustomerBatchgetResponse, error)
	ExternalcontactToServiceExternalUserid(req *ExternalcontactToServiceExternalUseridRequest) (*ExternalcontactToServiceExternalUseridResponse, error)
	DepartmentSimplelist(req *DepartmentSimplelistRequest) (*DepartmentSimplelistResponse, error)
	DepartmentGet(req *DepartmentGetRequest) (*DepartmentGetResponse, error)
	ServiceGetAppQrcode(req *ServiceGetAppQrcodeRequest) (*ServiceGetAppQrcodeResponse, error)
	KFGetCorpStatistic(req *KFGetCorpStatisticRequest) (*KFGetCorpStatisticResponse, error)
	KFGetServicerStatistic(req *KFGetServicerStatisticRequest) (*KFGetServicerStatisticResponse, error)
	ExmailGroupCreate(req *ExmailGroupCreateRequest) (*ExmailGroupCreateResponse, error)
	ExmailPublicmailCreate(req *ExmailPublicmailCreateRequest) (*ExmailPublicmailCreateResponse, error)
	ExmailAccountActEmail(req *ExmailAccountActEmailRequest) (*ExmailAccountActEmailResponse, error)
	ExmailUseroptionGet(req *ExmailUseroptionGetRequest) (*ExmailUseroptionGetResponse, error)
	ExmailMailGetNewcount(req *ExmailMailGetNewcountRequest) (*ExmailMailGetNewcountResponse, error)
	LicenseListActivedAccount(req *LicenseListActivedAccountRequest) (*LicenseListActivedAccountResponse, error)
	LicenseBatchGetActiveInfoByCode(req *LicenseBatchGetActiveInfoByCodeRequest) (*LicenseBatchGetActiveInfoByCodeResponse, error)
	LicenseActiveAccountByType(req *LicenseActiveAccountByTypeRequest) (*LicenseActiveAccountByTypeResponse, error)
	LicenseGetActiveInfoByUser(req *LicenseGetActiveInfoByUserRequest) (*LicenseGetActiveInfoByUserResponse, error)
	ServiceCorpidToOpencorpid(req *ServiceCorpidToOpencorpidRequest) (*ServiceCorpidToOpencorpidResponse, error)
	CorpgroupRuleListIDs(req *CorpgroupRuleListIDsRequest) (*CorpgroupRuleListIDsResponse, error)
	CorpgroupRuleDeleteRule(req *CorpgroupRuleDeleteRuleRequest) (*CorpgroupRuleDeleteRuleResponse, error)
	CorpgroupRuleGetRuleInfo(req *CorpgroupRuleGetRuleInfoRequest) (*CorpgroupRuleGetRuleInfoResponse, error)
	CorpgroupRuleAddRule(req *CorpgroupRuleAddRuleRequest) (*CorpgroupRuleAddRuleResponse, error)
	CorpgroupRuleModifyRule(req *CorpgroupRuleModifyRuleRequest) (*CorpgroupRuleModifyRuleResponse, error)
	LicenseCreateNewOrder(req *LicenseCreateNewOrderRequest) (*LicenseCreateNewOrderResponse, error)
	LicenseSubmitOrderJob(req *LicenseSubmitOrderJobRequest) (*LicenseSubmitOrderJobResponse, error)
	LicenseListOrder(req *LicenseListOrderRequest) (*LicenseListOrderResponse, error)
	LicenseGetOrder(req *LicenseGetOrderRequest) (*LicenseGetOrderResponse, error)
	LicenseListOrderAccount(req *LicenseListOrderAccountRequest) (*LicenseListOrderAccountResponse, error)
	LicenseBatchTransferLicense(req *LicenseBatchTransferLicenseRequest) (*LicenseBatchTransferLicenseResponse, error)
	ExternalcontactGroupchatOnjobTransfer(req *ExternalcontactGroupchatOnjobTransferRequest) (*ExternalcontactGroupchatOnjobTransferResponse, error)
	ServiceSchoolGetuserinfo3rd(req *ServiceSchoolGetuserinfo3rdRequest) (*ServiceSchoolGetuserinfo3rdResponse, error)
	SchoolGetuserinfo(req *SchoolGetuserinfoRequest) (*SchoolGetuserinfoResponse, error)
	SchoolLivingGetWatchStatV2(req *SchoolLivingGetWatchStatV2Request) (*SchoolLivingGetWatchStatV2Response, error)
	SchoolLivingGetUnwatchStatV2(req *SchoolLivingGetUnwatchStatV2Request) (*SchoolLivingGetUnwatchStatV2Response, error)
	CheckinPunchCorrection(req *CheckinPunchCorrectionRequest) (*CheckinPunchCorrectionResponse, error)
	CorpgroupUnionidToExternalUserid(req *CorpgroupUnionidToExternalUseridRequest) (*CorpgroupUnionidToExternalUseridResponse, error)
	CorpgroupCorpGetChainCorpinfo(req *CorpgroupCorpGetChainCorpinfoRequest) (*CorpgroupCorpGetChainCorpinfoResponse, error)
	CorpgroupImportChainContact(req *CorpgroupImportChainContactRequest) (*CorpgroupImportChainContactResponse, error)
	CorpgroupCorpRemoveCorp(req *CorpgroupCorpRemoveCorpRequest) (*CorpgroupCorpRemoveCorpResponse, error)
	CorpgroupGetresult(req *CorpgroupGetresultRequest) (*CorpgroupGetresultResponse, error)
	AuthGetuserdetail(req *AuthGetuserdetailRequest) (*AuthGetuserdetailResponse, error)
	LicenseGetAppLicenseInfo(req *LicenseGetAppLicenseInfoRequest) (*LicenseGetAppLicenseInfoResponse, error)
	WedriveMngCapacity(req *WedriveMngCapacityRequest) (*WedriveMngCapacityResponse, error)
	LicenseSetAutoActiveStatus(req *LicenseSetAutoActiveStatusRequest) (*LicenseSetAutoActiveStatusResponse, error)
	LicenseGetAutoActiveStatus(req *LicenseGetAutoActiveStatusRequest) (*LicenseGetAutoActiveStatusResponse, error)
	ExternalcontactFromServiceExternalUserid(req *ExternalcontactFromServiceExternalUseridRequest) (*ExternalcontactFromServiceExternalUseridResponse, error)
	UserGetUseridByEmail(req *UserGetUseridByEmailRequest) (*UserGetUseridByEmailResponse, error)
	ExternalpayGetPaymentInfo(req *ExternalpayGetPaymentInfoRequest) (*ExternalpayGetPaymentInfoResponse, error)
	KFKnowledgeListGroup(req *KFKnowledgeListGroupRequest) (*KFKnowledgeListGroupResponse, error)
	KFKnowledgeListIntent(req *KFKnowledgeListIntentRequest) (*KFKnowledgeListIntentResponse, error)
	UserListID(req *UserListIDRequest) (*UserListIDResponse, error)
	DevicedataGetCheckinData(req *DevicedataGetCheckinDataRequest) (*DevicedataGetCheckinDataResponse, error)
	DevicedataGetTemperatureData(req *DevicedataGetTemperatureDataRequest) (*DevicedataGetTemperatureDataResponse, error)
	DevicedataGetAccesscontrolData(req *DevicedataGetAccesscontrolDataRequest) (*DevicedataGetAccesscontrolDataResponse, error)
	DevicedataGetAccesscontrolRule(req *DevicedataGetAccesscontrolRuleRequest) (*DevicedataGetAccesscontrolRuleResponse, error)
	DevicedataAddAccesscontrolRule(req *DevicedataAddAccesscontrolRuleRequest) (*DevicedataAddAccesscontrolRuleResponse, error)
	LicenseBatchShareActiveCode(req *LicenseBatchShareActiveCodeRequest) (*LicenseBatchShareActiveCodeResponse, error)
	DevicedataGetAuthInfo(req *DevicedataGetAuthInfoRequest) (*DevicedataGetAuthInfoResponse, error)
	LicenseCancelOrder(req *LicenseCancelOrderRequest) (*LicenseCancelOrderResponse, error)
	IDconvertUnionidToExternalUserid(req *IDconvertUnionidToExternalUseridRequest) (*IDconvertUnionidToExternalUseridResponse, error)
	IDconvertExternalTagid(req *IDconvertExternalTagidRequest) (*IDconvertExternalTagidResponse, error)
	MediaGetUploadByURLResult(req *MediaGetUploadByURLResultRequest) (*MediaGetUploadByURLResultResponse, error)
	DevicedataModAccesscontrolRule(req *DevicedataModAccesscontrolRuleRequest) (*DevicedataModAccesscontrolRuleResponse, error)
	DevicedataDelAccesscontrolRule(req *DevicedataDelAccesscontrolRuleRequest) (*DevicedataDelAccesscontrolRuleResponse, error)
	ExternalcontactCheckFollowUser(req *ExternalcontactCheckFollowUserRequest) (*ExternalcontactCheckFollowUserResponse, error)
	LicenseSupportPolicyQuery(req *LicenseSupportPolicyQueryRequest) (*LicenseSupportPolicyQueryResponse, error)
	ServiceExternalcontactFinishExternalUseridMigration(req *ServiceExternalcontactFinishExternalUseridMigrationRequest) (*ServiceExternalcontactFinishExternalUseridMigrationResponse, error)
	CorpGetOpenidMigration(req *CorpGetOpenidMigrationRequest) (*CorpGetOpenidMigrationResponse, error)
	BatchUseridToOpenuserid(req *BatchUseridToOpenuseridRequest) (*BatchUseridToOpenuseridResponse, error)
	ExternalcontactGroupchatGetNewExternalUserid(req *ExternalcontactGroupchatGetNewExternalUseridRequest) (*ExternalcontactGroupchatGetNewExternalUseridResponse, error)
	IDconvertOpenKFid(req *IDconvertOpenKFidRequest) (*IDconvertOpenKFidResponse, error)
 // ChatdataKeywordDeleteRule(req *ChatdataKeywordDeleteRuleRequest) (*ChatdataKeywordDeleteRuleResponse, error) // TODO: 缺少实现或文档
 // ChatdataSyncMsg(req *ChatdataSyncMsgRequest) (*ChatdataSyncMsgResponse, error) // TODO: 缺少实现或文档
 // ChatdataKeywordGetHitMsgList(req *ChatdataKeywordGetHitMsgListRequest) (*ChatdataKeywordGetHitMsgListResponse, error) // TODO: 缺少实现或文档
	ExternalcontactCustomerAcquisitionDeleteLink(req *ExternalcontactCustomerAcquisitionDeleteLinkRequest) (*ExternalcontactCustomerAcquisitionDeleteLinkResponse, error)
	ExternalcontactCustomerAcquisitionCustomer(req *ExternalcontactCustomerAcquisitionCustomerRequest) (*ExternalcontactCustomerAcquisitionCustomerResponse, error)
	MiniapppayCreateOrder(req *MiniapppayCreateOrderRequest) (*MiniapppayCreateOrderResponse, error)
	MiniapppayGetOrder(req *MiniapppayGetOrderRequest) (*MiniapppayGetOrderResponse, error)
	MiniapppayCloseOrder(req *MiniapppayCloseOrderRequest) (*MiniapppayCloseOrderResponse, error)
	MiniapppayRefund(req *MiniapppayRefundRequest) (*MiniapppayRefundResponse, error)
	MiniapppayGetRefundDetail(req *MiniapppayGetRefundDetailRequest) (*MiniapppayGetRefundDetailResponse, error)
	CorpgroupBatchExternalUseridToPendingID(req *CorpgroupBatchExternalUseridToPendingIDRequest) (*CorpgroupBatchExternalUseridToPendingIDResponse, error)
	ExmailAppGetMailList(req *ExmailAppGetMailListRequest) (*ExmailAppGetMailListResponse, error)
	ExmailAppUpdateEmailAlias(req *ExmailAppUpdateEmailAliasRequest) (*ExmailAppUpdateEmailAliasResponse, error)
 // ChatdataSearchMsg(req *ChatdataSearchMsgRequest) (*ChatdataSearchMsgResponse, error) // TODO: 缺少实现或文档
	ExternalcontactCustomerAcquisitionStatistic(req *ExternalcontactCustomerAcquisitionStatisticRequest) (*ExternalcontactCustomerAcquisitionStatisticResponse, error)
	OaApprovalCreateTemplate(req *OaApprovalCreateTemplateRequest) (*OaApprovalCreateTemplateResponse, error)
	OaApprovalUpdateTemplate(req *OaApprovalUpdateTemplateRequest) (*OaApprovalUpdateTemplateResponse, error)
	CorpgroupCorpGetChainUserCustomID(req *CorpgroupCorpGetChainUserCustomIDRequest) (*CorpgroupCorpGetChainUserCustomIDResponse, error)
	CorpgroupGetCorpSharedChainList(req *CorpgroupGetCorpSharedChainListRequest) (*CorpgroupGetCorpSharedChainListResponse, error)
	ExmailAppComposeSend(req *ExmailAppComposeSendRequest) (*ExmailAppComposeSendResponse, error)
	WedocCreateDoc(req *WedocCreateDocRequest) (*WedocCreateDocResponse, error)
	WedocDocGetAuth(req *WedocDocGetAuthRequest) (*WedocDocGetAuthResponse, error)
	WedocCreateForm(req *WedocCreateFormRequest) (*WedocCreateFormResponse, error)
	ExternalcontactRemindGroupmsgSend(req *ExternalcontactRemindGroupmsgSendRequest) (*ExternalcontactRemindGroupmsgSendResponse, error)
	ExternalcontactCancelGroupmsgSend(req *ExternalcontactCancelGroupmsgSendRequest) (*ExternalcontactCancelGroupmsgSendResponse, error)
	ExternalcontactCancelMomentTask(req *ExternalcontactCancelMomentTaskRequest) (*ExternalcontactCancelMomentTaskResponse, error)
	WedocDocumentBatchUpdate(req *WedocDocumentBatchUpdateRequest) (*WedocDocumentBatchUpdateResponse, error)
	WedocSpreadsheetGetSheetRangeData(req *WedocSpreadsheetGetSheetRangeDataRequest) (*WedocSpreadsheetGetSheetRangeDataResponse, error)
	WedocSpreadsheetGetSheetProperties(req *WedocSpreadsheetGetSheetPropertiesRequest) (*WedocSpreadsheetGetSheetPropertiesResponse, error)
	OaCalendarUpdate(req *OaCalendarUpdateRequest) (*OaCalendarUpdateResponse, error)
	OaCalendarGet(req *OaCalendarGetRequest) (*OaCalendarGetResponse, error)
	OaCalendarDel(req *OaCalendarDelRequest) (*OaCalendarDelResponse, error)
	OaScheduleUpdate(req *OaScheduleUpdateRequest) (*OaScheduleUpdateResponse, error)
	OaScheduleAddAttendees(req *OaScheduleAddAttendeesRequest) (*OaScheduleAddAttendeesResponse, error)
	OaScheduleDelAttendees(req *OaScheduleDelAttendeesRequest) (*OaScheduleDelAttendeesResponse, error)
	OaScheduleGetByCalendar(req *OaScheduleGetByCalendarRequest) (*OaScheduleGetByCalendarResponse, error)
	OaScheduleGet(req *OaScheduleGetRequest) (*OaScheduleGetResponse, error)
	OaScheduleDel(req *OaScheduleDelRequest) (*OaScheduleDelResponse, error)
	WedocDocShare(req *WedocDocShareRequest) (*WedocDocShareResponse, error)
	WedocGetDocBaseInfo(req *WedocGetDocBaseInfoRequest) (*WedocGetDocBaseInfoResponse, error)
	WedocDelDoc(req *WedocDelDocRequest) (*WedocDelDocResponse, error)
	WedocRenameDoc(req *WedocRenameDocRequest) (*WedocRenameDocResponse, error)
	WedocModDocJoinRule(req *WedocModDocJoinRuleRequest) (*WedocModDocJoinRuleResponse, error)
	WedocModDocMember(req *WedocModDocMemberRequest) (*WedocModDocMemberResponse, error)
	WedocModDocSaftySetting(req *WedocModDocSaftySettingRequest) (*WedocModDocSaftySettingResponse, error)
	WedocModifyForm(req *WedocModifyFormRequest) (*WedocModifyFormResponse, error)
	WedocGetFormInfo(req *WedocGetFormInfoRequest) (*WedocGetFormInfoResponse, error)
	WedocGetFormStatistic(req *WedocGetFormStatisticRequest) (*WedocGetFormStatisticResponse, error)
	WedocGetFormAnswer(req *WedocGetFormAnswerRequest) (*WedocGetFormAnswerResponse, error)
	WedriveSpaceRename(req *WedriveSpaceRenameRequest) (*WedriveSpaceRenameResponse, error)
	WedriveSpaceDismiss(req *WedriveSpaceDismissRequest) (*WedriveSpaceDismissResponse, error)
	WedriveSpaceInfo(req *WedriveSpaceInfoRequest) (*WedriveSpaceInfoResponse, error)
	WedriveSpaceAclDel(req *WedriveSpaceAclDelRequest) (*WedriveSpaceAclDelResponse, error)
	WedriveSpaceSetting(req *WedriveSpaceSettingRequest) (*WedriveSpaceSettingResponse, error)
	WedriveSpaceShare(req *WedriveSpaceShareRequest) (*WedriveSpaceShareResponse, error)
	WedriveNewSpaceInfo(req *WedriveNewSpaceInfoRequest) (*WedriveNewSpaceInfoResponse, error)
	WedriveFileUpload(req *WedriveFileUploadRequest) (*WedriveFileUploadResponse, error)
	WedriveFileDownload(req *WedriveFileDownloadRequest) (*WedriveFileDownloadResponse, error)
	WedriveFileCreate(req *WedriveFileCreateRequest) (*WedriveFileCreateResponse, error)
	WedriveFileRename(req *WedriveFileRenameRequest) (*WedriveFileRenameResponse, error)
	WedriveFileMove(req *WedriveFileMoveRequest) (*WedriveFileMoveResponse, error)
	WedriveFileDelete(req *WedriveFileDeleteRequest) (*WedriveFileDeleteResponse, error)
	WedriveFileInfo(req *WedriveFileInfoRequest) (*WedriveFileInfoResponse, error)
	WedriveFileAclDel(req *WedriveFileAclDelRequest) (*WedriveFileAclDelResponse, error)
	WedriveFileSetting(req *WedriveFileSettingRequest) (*WedriveFileSettingResponse, error)
	WedriveFileShare(req *WedriveFileShareRequest) (*WedriveFileShareResponse, error)
	WedriveGetFilePermission(req *WedriveGetFilePermissionRequest) (*WedriveGetFilePermissionResponse, error)
	WedriveFileSecureSetting(req *WedriveFileSecureSettingRequest) (*WedriveFileSecureSettingResponse, error)
	ExmailAppReadMail(req *ExmailAppReadMailRequest) (*ExmailAppReadMailResponse, error)
	ExmailAppGetEmailAlias(req *ExmailAppGetEmailAliasRequest) (*ExmailAppGetEmailAliasResponse, error)
	ExmailGroupUpdate(req *ExmailGroupUpdateRequest) (*ExmailGroupUpdateResponse, error)
	ExmailGroupDelete(req *ExmailGroupDeleteRequest) (*ExmailGroupDeleteResponse, error)
	ExmailGroupGet(req *ExmailGroupGetRequest) (*ExmailGroupGetResponse, error)
	ExmailGroupSearch(req *ExmailGroupSearchRequest) (*ExmailGroupSearchResponse, error)
	ExmailPublicmailUpdate(req *ExmailPublicmailUpdateRequest) (*ExmailPublicmailUpdateResponse, error)
	ExmailPublicmailDelete(req *ExmailPublicmailDeleteRequest) (*ExmailPublicmailDeleteResponse, error)
	ExmailPublicmailGet(req *ExmailPublicmailGetRequest) (*ExmailPublicmailGetResponse, error)
	ExmailPublicmailSearch(req *ExmailPublicmailSearchRequest) (*ExmailPublicmailSearchResponse, error)
	WedriveFileUploadFinish(req *WedriveFileUploadFinishRequest) (*WedriveFileUploadFinishResponse, error)
	ExmailUseroptionUpdate(req *ExmailUseroptionUpdateRequest) (*ExmailUseroptionUpdateResponse, error)
	OaJournalDownloadWedriveFile(req *OaJournalDownloadWedriveFileRequest) (*OaJournalDownloadWedriveFileResponse, error)
	CheckinDelCheckinOption(req *CheckinDelCheckinOptionRequest) (*CheckinDelCheckinOptionResponse, error)
	PaytoolOpenOrder(req *PaytoolOpenOrderRequest) (*PaytoolOpenOrderResponse, error)
	PaytoolCloseOrder(req *PaytoolCloseOrderRequest) (*PaytoolCloseOrderResponse, error)
	PaytoolGetOrderList(req *PaytoolGetOrderListRequest) (*PaytoolGetOrderListResponse, error)
	PaytoolGetOrderDetail(req *PaytoolGetOrderDetailRequest) (*PaytoolGetOrderDetailResponse, error)
	SecurityGetFileOperRecord(req *SecurityGetFileOperRecordRequest) (*SecurityGetFileOperRecordResponse, error)
	ExternalpayGetFundFlow(req *ExternalpayGetFundFlowRequest) (*ExternalpayGetFundFlowResponse, error)
	MiniapppayGetSign(req *MiniapppayGetSignRequest) (*MiniapppayGetSignResponse, error)
	MeetingGetAttendeeList(req *MeetingGetAttendeeListRequest) (*MeetingGetAttendeeListResponse, error)
	MeetingGetRealtimeAttendeeList(req *MeetingGetRealtimeAttendeeListRequest) (*MeetingGetRealtimeAttendeeListResponse, error)
	MeetingGetInvitees(req *MeetingGetInviteesRequest) (*MeetingGetInviteesResponse, error)
	MeetingSetInvitees(req *MeetingSetInviteesRequest) (*MeetingSetInviteesResponse, error)
	MeetingWaitingroomGetCurrentUserList(req *MeetingWaitingroomGetCurrentUserListRequest) (*MeetingWaitingroomGetCurrentUserListResponse, error)
	MeetingWaitingroomGetUserList(req *MeetingWaitingroomGetUserListRequest) (*MeetingWaitingroomGetUserListResponse, error)
	MeetingCheckDeviceInMeeting(req *MeetingCheckDeviceInMeetingRequest) (*MeetingCheckDeviceInMeetingResponse, error)
	MeetingRealcontrolSet(req *MeetingRealcontrolSetRequest) (*MeetingRealcontrolSetResponse, error)
	MeetingRealcontrolSetCohost(req *MeetingRealcontrolSetCohostRequest) (*MeetingRealcontrolSetCohostResponse, error)
	MeetingRealcontrolKickoutUsers(req *MeetingRealcontrolKickoutUsersRequest) (*MeetingRealcontrolKickoutUsersResponse, error)
	MeetingRealcontrolMuteUser(req *MeetingRealcontrolMuteUserRequest) (*MeetingRealcontrolMuteUserResponse, error)
	MeetingRealcontrolCloseScreenShare(req *MeetingRealcontrolCloseScreenShareRequest) (*MeetingRealcontrolCloseScreenShareResponse, error)
	MeetingRealcontrolManageWaitingRoomUsers(req *MeetingRealcontrolManageWaitingRoomUsersRequest) (*MeetingRealcontrolManageWaitingRoomUsersResponse, error)
	MeetingRealcontrolDismiss(req *MeetingRealcontrolDismissRequest) (*MeetingRealcontrolDismissResponse, error)
	MeetingRealcontrolSetNicknames(req *MeetingRealcontrolSetNicknamesRequest) (*MeetingRealcontrolSetNicknamesResponse, error)
	MeetingRealcontrolSwitchUserVideo(req *MeetingRealcontrolSwitchUserVideoRequest) (*MeetingRealcontrolSwitchUserVideoResponse, error)
	MeetingRecordList(req *MeetingRecordListRequest) (*MeetingRecordListResponse, error)
	MeetingRecordGetFileList(req *MeetingRecordGetFileListRequest) (*MeetingRecordGetFileListResponse, error)
	MeetingRecordGetFile(req *MeetingRecordGetFileRequest) (*MeetingRecordGetFileResponse, error)
	MeetingRecordDelete(req *MeetingRecordDeleteRequest) (*MeetingRecordDeleteResponse, error)
	MeetingRecordDeleteFile(req *MeetingRecordDeleteFileRequest) (*MeetingRecordDeleteFileResponse, error)
	MeetingRecordUpdateSharingConfig(req *MeetingRecordUpdateSharingConfigRequest) (*MeetingRecordUpdateSharingConfigResponse, error)
	MeetingRecordGetStatistics(req *MeetingRecordGetStatisticsRequest) (*MeetingRecordGetStatisticsResponse, error)
	MeetingRecordTranscriptGetDetail(req *MeetingRecordTranscriptGetDetailRequest) (*MeetingRecordTranscriptGetDetailResponse, error)
	MeetingRecordTranscriptGetParagraphList(req *MeetingRecordTranscriptGetParagraphListRequest) (*MeetingRecordTranscriptGetParagraphListResponse, error)
	MeetingRecordTranscriptSearch(req *MeetingRecordTranscriptSearchRequest) (*MeetingRecordTranscriptSearchResponse, error)
	IDconvertConvertTmpExternalUserid(req *IDconvertConvertTmpExternalUseridRequest) (*IDconvertConvertTmpExternalUseridResponse, error)
	ServiceGetCustomizedAuthURL(req *ServiceGetCustomizedAuthURLRequest) (*ServiceGetCustomizedAuthURLResponse, error)
	MeetingMraQueryStatus(req *MeetingMraQueryStatusRequest) (*MeetingMraQueryStatusResponse, error)
	MeetingMraSetDefaultLayout(req *MeetingMraSetDefaultLayoutRequest) (*MeetingMraSetDefaultLayoutResponse, error)
	MeetingMraSetRaiseHand(req *MeetingMraSetRaiseHandRequest) (*MeetingMraSetRaiseHandResponse, error)
	MeetingMraHangup(req *MeetingMraHangupRequest) (*MeetingMraHangupResponse, error)
	MeetingRoomsBook(req *MeetingRoomsBookRequest) (*MeetingRoomsBookResponse, error)
	MeetingRoomsRelease(req *MeetingRoomsReleaseRequest) (*MeetingRoomsReleaseResponse, error)
	MeetingRoomsGetInfo(req *MeetingRoomsGetInfoRequest) (*MeetingRoomsGetInfoResponse, error)
	MeetingEnrollQueryByTmpOpenid(req *MeetingEnrollQueryByTmpOpenidRequest) (*MeetingEnrollQueryByTmpOpenidResponse, error)
	MeetingRoomsList(req *MeetingRoomsListRequest) (*MeetingRoomsListResponse, error)
	MeetingRoomsListMeetings(req *MeetingRoomsListMeetingsRequest) (*MeetingRoomsListMeetingsResponse, error)
	MeetingEnrollSetConfig(req *MeetingEnrollSetConfigRequest) (*MeetingEnrollSetConfigResponse, error)
	MeetingRoomsListDevices(req *MeetingRoomsListDevicesRequest) (*MeetingRoomsListDevicesResponse, error)
	MeetingRoomsListControllers(req *MeetingRoomsListControllersRequest) (*MeetingRoomsListControllersResponse, error)
	MeetingEnrollGetConfig(req *MeetingEnrollGetConfigRequest) (*MeetingEnrollGetConfigResponse, error)
	MeetingRoomsGetConfig(req *MeetingRoomsGetConfigRequest) (*MeetingRoomsGetConfigResponse, error)
	MeetingRoomsCall(req *MeetingRoomsCallRequest) (*MeetingRoomsCallResponse, error)
	MeetingRoomsCancelCall(req *MeetingRoomsCancelCallRequest) (*MeetingRoomsCancelCallResponse, error)
	MeetingRoomsGetResponseStatus(req *MeetingRoomsGetResponseStatusRequest) (*MeetingRoomsGetResponseStatusResponse, error)
	MeetingEnrollApprove(req *MeetingEnrollApproveRequest) (*MeetingEnrollApproveResponse, error)
	MeetingRoomsGetInventory(req *MeetingRoomsGetInventoryRequest) (*MeetingRoomsGetInventoryResponse, error)
	MeetingEnrollList(req *MeetingEnrollListRequest) (*MeetingEnrollListResponse, error)
	MeetingEnrollImport(req *MeetingEnrollImportRequest) (*MeetingEnrollImportResponse, error)
	MeetingEnrollDelete(req *MeetingEnrollDeleteRequest) (*MeetingEnrollDeleteResponse, error)
	MeetingCreateCustomerShortURL(req *MeetingCreateCustomerShortURLRequest) (*MeetingCreateCustomerShortURLResponse, error)
	MeetingGetCustomerShortURL(req *MeetingGetCustomerShortURLRequest) (*MeetingGetCustomerShortURLResponse, error)
	MeetingGetQuality(req *MeetingGetQualityRequest) (*MeetingGetQualityResponse, error)
	MeetingPhoneCallout(req *MeetingPhoneCalloutRequest) (*MeetingPhoneCalloutResponse, error)
	MeetingPhoneGetCalloutStatus(req *MeetingPhoneGetCalloutStatusRequest) (*MeetingPhoneGetCalloutStatusResponse, error)
	MeetingPhoneGetTmpOpenid(req *MeetingPhoneGetTmpOpenidRequest) (*MeetingPhoneGetTmpOpenidResponse, error)
	MeetingPollCreateTheme(req *MeetingPollCreateThemeRequest) (*MeetingPollCreateThemeResponse, error)
	MeetingPollUpdateTheme(req *MeetingPollUpdateThemeRequest) (*MeetingPollUpdateThemeResponse, error)
	MeetingPollGetPollList(req *MeetingPollGetPollListRequest) (*MeetingPollGetPollListResponse, error)
	MeetingPollGetThemeInfo(req *MeetingPollGetThemeInfoRequest) (*MeetingPollGetThemeInfoResponse, error)
	MeetingPollGetPollDetail(req *MeetingPollGetPollDetailRequest) (*MeetingPollGetPollDetailResponse, error)
	MeetingPollDelete(req *MeetingPollDeleteRequest) (*MeetingPollDeleteResponse, error)
	MeetingPollStart(req *MeetingPollStartRequest) (*MeetingPollStartResponse, error)
	MeetingPollFinish(req *MeetingPollFinishRequest) (*MeetingPollFinishResponse, error)
	MeetingWebinarCreate(req *MeetingWebinarCreateRequest) (*MeetingWebinarCreateResponse, error)
	MeetingWebinarUpdate(req *MeetingWebinarUpdateRequest) (*MeetingWebinarUpdateResponse, error)
	MeetingLayoutListTemplate(req *MeetingLayoutListTemplateRequest) (*MeetingLayoutListTemplateResponse, error)
	MeetingLayoutAdd(req *MeetingLayoutAddRequest) (*MeetingLayoutAddResponse, error)
	MeetingLayoutUpdate(req *MeetingLayoutUpdateRequest) (*MeetingLayoutUpdateResponse, error)
	MeetingLayoutSetDefault(req *MeetingLayoutSetDefaultRequest) (*MeetingLayoutSetDefaultResponse, error)
	MeetingLayoutAddBackground(req *MeetingLayoutAddBackgroundRequest) (*MeetingLayoutAddBackgroundResponse, error)
	MeetingLayoutSetDefaultBackground(req *MeetingLayoutSetDefaultBackgroundRequest) (*MeetingLayoutSetDefaultBackgroundResponse, error)
	MeetingLayoutDeleteBackground(req *MeetingLayoutDeleteBackgroundRequest) (*MeetingLayoutDeleteBackgroundResponse, error)
	MeetingLayoutBatchDeleteBackground(req *MeetingLayoutBatchDeleteBackgroundRequest) (*MeetingLayoutBatchDeleteBackgroundResponse, error)
	MeetingLayoutListBackground(req *MeetingLayoutListBackgroundRequest) (*MeetingLayoutListBackgroundResponse, error)
	MeetingWebinarGet(req *MeetingWebinarGetRequest) (*MeetingWebinarGetResponse, error)
	MeetingAdvancedLayoutAdd(req *MeetingAdvancedLayoutAddRequest) (*MeetingAdvancedLayoutAddResponse, error)
	MeetingAdvancedLayoutList(req *MeetingAdvancedLayoutListRequest) (*MeetingAdvancedLayoutListResponse, error)
	MeetingAdvancedLayoutGetUserLayout(req *MeetingAdvancedLayoutGetUserLayoutRequest) (*MeetingAdvancedLayoutGetUserLayoutResponse, error)
	MeetingAdvancedLayoutBatchDelete(req *MeetingAdvancedLayoutBatchDeleteRequest) (*MeetingAdvancedLayoutBatchDeleteResponse, error)
	MeetingAdvancedLayoutUpdate(req *MeetingAdvancedLayoutUpdateRequest) (*MeetingAdvancedLayoutUpdateResponse, error)
	MeetingAdvancedLayoutApply(req *MeetingAdvancedLayoutApplyRequest) (*MeetingAdvancedLayoutApplyResponse, error)
	MeetingWebinarCancel(req *MeetingWebinarCancelRequest) (*MeetingWebinarCancelResponse, error)
	MeetingWebinarListGuest(req *MeetingWebinarListGuestRequest) (*MeetingWebinarListGuestResponse, error)
	MeetingWebinarUpdateGuestList(req *MeetingWebinarUpdateGuestListRequest) (*MeetingWebinarUpdateGuestListResponse, error)
	MeetingWebinarEnrollQueryByTmpOpenid(req *MeetingWebinarEnrollQueryByTmpOpenidRequest) (*MeetingWebinarEnrollQueryByTmpOpenidResponse, error)
	MeetingWebinarEnrollGetConfig(req *MeetingWebinarEnrollGetConfigRequest) (*MeetingWebinarEnrollGetConfigResponse, error)
	MeetingWebinarEnrollSetConfig(req *MeetingWebinarEnrollSetConfigRequest) (*MeetingWebinarEnrollSetConfigResponse, error)
	MeetingWebinarEnrollList(req *MeetingWebinarEnrollListRequest) (*MeetingWebinarEnrollListResponse, error)
	MeetingWebinarEnrollApprove(req *MeetingWebinarEnrollApproveRequest) (*MeetingWebinarEnrollApproveResponse, error)
	MeetingWebinarEnrollImport(req *MeetingWebinarEnrollImportRequest) (*MeetingWebinarEnrollImportResponse, error)
	MeetingWebinarEnrollDelete(req *MeetingWebinarEnrollDeleteRequest) (*MeetingWebinarEnrollDeleteResponse, error)
	MeetingWebinarUpdateWarmUp(req *MeetingWebinarUpdateWarmUpRequest) (*MeetingWebinarUpdateWarmUpResponse, error)
	LicenseNewOrderJobResult(req *LicenseNewOrderJobResultRequest) (*LicenseNewOrderJobResultResponse, error)
	LicenseGetUnionOrder(req *LicenseGetUnionOrderRequest) (*LicenseGetUnionOrderResponse, error)
	AppchatUpdate(req *AppchatUpdateRequest) (*AppchatUpdateResponse, error)
	AppchatGet(req *AppchatGetRequest) (*AppchatGetResponse, error)
	SecurityTrustdeviceReject(req *SecurityTrustdeviceRejectRequest) (*SecurityTrustdeviceRejectResponse, error)
	MiniapppayUploadImage(req *MiniapppayUploadImageRequest) (*MiniapppayUploadImageResponse, error)
	MiniapppayApplyMch(req *MiniapppayApplyMchRequest) (*MiniapppayApplyMchResponse, error)
	MiniapppayGetApplymentStatus(req *MiniapppayGetApplymentStatusRequest) (*MiniapppayGetApplymentStatusResponse, error)
	MeetingGetGuests(req *MeetingGetGuestsRequest) (*MeetingGetGuestsResponse, error)
	MeetingSetGuests(req *MeetingSetGuestsRequest) (*MeetingSetGuestsResponse, error)
	AgentGetPermissions(req *AgentGetPermissionsRequest) (*AgentGetPermissionsResponse, error)
	HrGetFields(req *HrGetFieldsRequest) (*HrGetFieldsResponse, error)
	HrGetStaffInfo(req *HrGetStaffInfoRequest) (*HrGetStaffInfoResponse, error)
	HrUpdateStaffInfo(req *HrUpdateStaffInfoRequest) (*HrUpdateStaffInfoResponse, error)
	ServiceMediaUpload(req *ServiceMediaUploadRequest) (*ServiceMediaUploadResponse, error)
	ExmailVipBatchAdd(req *ExmailVipBatchAddRequest) (*ExmailVipBatchAddResponse, error)
	ExmailVipBatchDel(req *ExmailVipBatchDelRequest) (*ExmailVipBatchDelResponse, error)
	ExmailVipList(req *ExmailVipListRequest) (*ExmailVipListResponse, error)
	KFGetStatistic(req *KFGetStatisticRequest) (*KFGetStatisticResponse, error)
	ServiceFinishOpenidMigration(req *ServiceFinishOpenidMigrationRequest) (*ServiceFinishOpenidMigrationResponse, error)
	LicensePayJobResult(req *LicensePayJobResultRequest) (*LicensePayJobResultResponse, error)
	ExternalcontactContactList(req *ExternalcontactContactListRequest) (*ExternalcontactContactListResponse, error)
	PaytoolGetInvoiceList(req *PaytoolGetInvoiceListRequest) (*PaytoolGetInvoiceListResponse, error)
	PaytoolMarkInvoiceStatus(req *PaytoolMarkInvoiceStatusRequest) (*PaytoolMarkInvoiceStatusResponse, error)
	ExternalcontactCustomerAcquisitionGet(req *ExternalcontactCustomerAcquisitionGetRequest) (*ExternalcontactCustomerAcquisitionGetResponse, error)
 // ChatdataGroupchatGet(req *ChatdataGroupchatGetRequest) (*ChatdataGroupchatGetResponse, error) // TODO: 缺少实现或文档
 // ChatdataSearchChat(req *ChatdataSearchChatRequest) (*ChatdataSearchChatResponse, error) // TODO: 缺少实现或文档
	AuthGetTfaInfo(req *AuthGetTfaInfoRequest) (*AuthGetTfaInfoResponse, error)
	UserTfaSucc(req *UserTfaSuccRequest) (*UserTfaSuccResponse, error)
	SecurityVipBatchAddJobResult(req *SecurityVipBatchAddJobResultRequest) (*SecurityVipBatchAddJobResultResponse, error)
	SecurityVipBatchDelJobResult(req *SecurityVipBatchDelJobResultRequest) (*SecurityVipBatchDelJobResultResponse, error)
	SecurityVipList(req *SecurityVipListRequest) (*SecurityVipListResponse, error)
	MeetingVipBatchAddJobResult(req *MeetingVipBatchAddJobResultRequest) (*MeetingVipBatchAddJobResultResponse, error)
	MeetingVipBatchDelJobResult(req *MeetingVipBatchDelJobResultRequest) (*MeetingVipBatchDelJobResultResponse, error)
	MeetingVipList(req *MeetingVipListRequest) (*MeetingVipListResponse, error)
	WedriveVipBatchAdd(req *WedriveVipBatchAddRequest) (*WedriveVipBatchAddResponse, error)
	WedriveVipBatchDel(req *WedriveVipBatchDelRequest) (*WedriveVipBatchDelResponse, error)
	WedriveVipList(req *WedriveVipListRequest) (*WedriveVipListResponse, error)
	WedocVipBatchAdd(req *WedocVipBatchAddRequest) (*WedocVipBatchAddResponse, error)
	WedocVipBatchDel(req *WedocVipBatchDelRequest) (*WedocVipBatchDelResponse, error)
	WedocVipList(req *WedocVipListRequest) (*WedocVipListResponse, error)
 // ChatdataGetagreestatusRoom(req *ChatdataGetagreestatusRoomRequest) (*ChatdataGetagreestatusRoomResponse, error) // TODO: 缺少实现或文档
	IDconvertUpgradeChatidForNewCorp(req *IDconvertUpgradeChatidForNewCorpRequest) (*IDconvertUpgradeChatidForNewCorpResponse, error)
	ServiceCustomerAcquisitionGetBillList(req *ServiceCustomerAcquisitionGetBillListRequest) (*ServiceCustomerAcquisitionGetBillListResponse, error)
	ExternalcontactCustomerAcquisitionCreateOnceKey(req *ExternalcontactCustomerAcquisitionCreateOnceKeyRequest) (*ExternalcontactCustomerAcquisitionCreateOnceKeyResponse, error)
	ExternalcontactCustomerAcquisitionGetCompAuthInfo(req *ExternalcontactCustomerAcquisitionGetCompAuthInfoRequest) (*ExternalcontactCustomerAcquisitionGetCompAuthInfoResponse, error)
	AgentClaimCustomizedApp(req *AgentClaimCustomizedAppRequest) (*AgentClaimCustomizedAppResponse, error)
	// ChatdataExportGetJobStatus(req *ChatdataExportGetJobStatusRequest) (*ChatdataExportGetJobStatusResponse, error) // TODO: 缺少 API 文档
	CheckinAddCheckinRecord(req *CheckinAddCheckinRecordRequest) (*CheckinAddCheckinRecordResponse, error)
	MeetingStatisticsGetStartList(req *MeetingStatisticsGetStartListRequest) (*MeetingStatisticsGetStartListResponse, error)
	AdvancedFeatureSetApprovalDetail(req *AdvancedFeatureSetApprovalDetailRequest) (*AdvancedFeatureSetApprovalDetailResponse, error)
	AdvancedFeatureGetApplyIDList(req *AdvancedFeatureGetApplyIDListRequest) (*AdvancedFeatureGetApplyIDListResponse, error)
	AdvancedFeatureGetApprovalInfo(req *AdvancedFeatureGetApprovalInfoRequest) (*AdvancedFeatureGetApprovalInfoResponse, error)
	WedocImageUpload(req *WedocImageUploadRequest) (*WedocImageUploadResponse, error)
}

type Config struct {
	// CorpId         string
	// ProviderSecret string
	SuiteId     string
	SuiteSecret string
	SuiteToken  string
	SuiteAesKey string
	Debug       bool
}

type client struct {
	Host        string
	SuiteId     string
	SuiteSecret string
	Debug       bool

	imp          impls
	impGen       implsGenerated
	expireHandle func(corpId string) string
}

// New 创建客户端
func New(cfg Config) Client {
	c := &client{
		Host:        utils.Default(viper.GetString("wxwork.host"), os.Getenv("WXWORK_HOST"), DefaultHost),
		SuiteId:     cfg.SuiteId,
		SuiteSecret: cfg.SuiteSecret,
		Debug:       cfg.Debug,
	}

	c.init()
	return c
}

type MsgPayload interface {
	isMsgPayload()
}

// init
func (c *client) init() *client {
	c.imp.installAll(c)
	c.impGen.installAll(c)
	return c
}

// getUrl 获取请求地址
func (c *client) getUrl(path string) string {
	p, err := url.JoinPath(c.Host, path)
	if err != nil {
		panic(err)
	}

	return p
}

// HandleTokenExpired 处理token过期
func (c *client) HandleTokenExpired(fn func(corpId string) string) {
	c.expireHandle = fn
}

// HandleTokenExpired 处理token过期
func (c *client) handleTokenExpired(corpId string) string {
	if c.expireHandle != nil {
		return c.expireHandle(corpId)
	}

	return ""
}

func parseDuration(expireIn int) time.Duration {
	return time.Duration(expireIn) * time.Second
}

const MAX_RETRY = 3

func retryAccessToken[Resp any](c *client, corpId string, fn func(accessToken string) (Resp, error)) func(string) (Resp, error) {
	return func(accessToken string) (q Resp, e error) {
		for i := 0; i < MAX_RETRY; i++ {
			resp, err := fn(accessToken)
			if err != nil {
				if errs, ok := err.(*RespError); ok && errs.Errcode == 42001 {
					accessToken = c.handleTokenExpired(corpId)
					continue
				}
			}
			return resp, nil
		}

		e = errors.New("out of max retry")
		return
	}
}
